services:
    nginx:
        ports:
            - target: 80
              published: 8000
        networks:
            - laravel
        build:
            context: ./.docker
            dockerfile: nginx.Dockerfile
    php:
        networks:
            - laravel
        volumes:
            - type: bind
              source: .
              target: /srv/laravel
        build:
            context: .
            dockerfile: .docker/php.Dockerfile

networks:
    laravel:
