services:
    nginx:
        build:
            context: .
            dockerfile: .docker/Dockerfile
            target: nginx
        container_name: nginx
        networks:
            - laravel
        ports:
            - target: 80
              published: 8000
    php:
        build:
            context: .
            dockerfile: .docker/Dockerfile
            target: php
        container_name: php
        networks:
            - laravel
        user: $DOCKER_USER_ID:$DOCKER_GROUP_ID
        volumes:
            - type: bind
              source: .
              target: /srv/laravel
            - type: bind
              source: .docker/.composer
              target: /.composer
    postgres:
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: $DB_PASSWORD
        image: postgres:15.2-bullseye
        networks:
            - laravel
        volumes:
            - type: volume
              source: postgres
              target: /var/lib/postgresql/data
    adminer:
        container_name: adminer
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        image: adminer:4.8.1-standalone
        networks:
            - laravel
        ports:
            - target: 8080
              published: 8080
    redis:
        container_name: redis
        image: redis:7.0.9-bullseye
        networks:
            - laravel
        ports:
            - target: 6379
              published: 6379

networks:
    laravel:

volumes:
    postgres:
