services:
    nginx:
        build:
            context: ./.docker
            dockerfile: nginx.Dockerfile
        networks:
            - laravel
        ports:
            - target: 80
              published: 8000
    php:
        build:
            context: .
            dockerfile: .docker/php.Dockerfile
        networks:
            - laravel
        volumes:
            - type: bind
              source: .
              target: /srv/laravel

networks:
    laravel:
