services:
    nginx:
        container_name: nginx
        image: oorcun/laravel:nginx
        networks:
            - laravel
        ports:
            - target: 80
              published: 80
    php:
        container_name: php
        image: oorcun/laravel:php
        networks:
            - laravel
        volumes:
            - type: bind
              source: .env
              target: /srv/laravel/.env
    postgres:
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: $DB_PASSWORD
        image: postgres:15.2-bullseye
        networks:
            - laravel
        volumes:
            - type: volume
              source: postgres
              target: /var/lib/postgresql/data
    redis:
        container_name: redis
        image: redis:7.0.9-bullseye
        networks:
            - laravel

networks:
    laravel:

volumes:
    postgres:
