services:
    nginx:
        build:
            context: ./.docker
            dockerfile: nginx.Dockerfile
        container_name: nginx
        networks:
            - laravel
        ports:
            - target: 80
              published: 8000
    php:
        build:
            context: .
            dockerfile: .docker/php.production.Dockerfile
        container_name: php
        networks:
            - laravel
        user: $DOCKER_USER_ID:$DOCKER_GROUP_ID
        volumes:
            - type: bind
              source: .
              target: /srv/laravel
    postgres:
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: $DB_PASSWORD
        image: postgres:15.2-bullseye
        networks:
            - laravel
        volumes:
            - type: volume
              source: postgres
              target: /var/lib/postgresql/data
    redis:
        container_name: redis
        image: redis:7.0.9-bullseye
        networks:
            - laravel

networks:
    laravel:

volumes:
    postgres:
