services:
    nginx:
        build:
            context: .
            dockerfile: .docker/Dockerfile
            target: nginx
        container_name: nginx
    php:
        build:
            context: .
            dockerfile: .docker/Dockerfile
            target: php-production
        container_name: php
