services:
    nginx:
        build:
            context: ./.docker
            dockerfile: nginx.Dockerfile
        container_name: nginx
    php:
        build:
            context: .
            dockerfile: .docker/php.production.Dockerfile
        container_name: php
