services:
    nginx:
        build:
            context: ./.docker
            dockerfile: nginx.Dockerfile
        container_name: nginx
        networks:
            - laravel
        ports:
            - target: 80
              published: 8000
    php:
        build:
            context: .
            dockerfile: .docker/php.Dockerfile
        container_name: php
        networks:
            - laravel
        user: $DOCKER_USER_ID:$DOCKER_GROUP_ID
        volumes:
            - type: bind
              source: .
              target: /srv/laravel
    postgres:
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_DB: laravel
        image: postgres:15.2-bullseye
        networks:
            - laravel
        volumes:
            - type: volume
              source: postgres
              target: /var/lib/postgresql/data
    adminer:
        container_name: adminer
        image: adminer:4.8.1-standalone
        networks:
            - laravel
        ports:
            - target: 8080
              published: 8080
    redis:
        container_name: redis
        image: redis:7.0.9-bullseye
        networks:
            - laravel
    redisinsight:
        container_name: redisinsight
        image: redislabs/redisinsight:1.13.1
        networks:
            - laravel
        ports:
            - target: 8001
              published: 8001

networks:
    laravel:

volumes:
    postgres:
