services:
    nginx:
        build:
            context: ./.docker
            dockerfile: nginx.Dockerfile
        container_name: nginx
        networks:
            - laravel
        ports:
            - target: 80
              published: 8000
    php:
        build:
            context: .
            dockerfile: .docker/php.Dockerfile
        container_name: php
        networks:
            - laravel
        volumes:
            - type: bind
              source: .
              target: /srv/laravel
    postgres:
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: RAjmpEr6zL7wBBNYX9Xp8FIKorU4kLFf
            POSTGRES_DB: laravel
        image: postgres:15.2
        networks:
            - laravel
        volumes:
            - type: volume
              source: postgres
              target: /var/lib/postgresql/data
    adminer:
        container_name: adminer
        image: adminer:4.8.1
        networks:
            - laravel
        ports:
            - target: 8080
              published: 8080

networks:
    laravel:

volumes:
    postgres:
